package com.hbm.ntm.common.item;

import java.util.List;
import java.util.Locale;
import java.util.function.Supplier;
import net.minecraft.ChatFormatting;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.util.RandomSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.level.Level;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public class RtgPelletItem extends Item {
    public enum HalfLifeType {
        LONG,
        MEDIUM,
        SHORT
    }

    private static final String TAG_DEPLETION = "PELLET_DEPLETION";

    private static final String[] FACTS = new String[] {
        "One gram of Pu-238 costs $8,000.",
        "One gram of Pu-238 produces just under half a Watt of decay heat.",
        "The typical plutonium RTG contains close to eight kilograms of Pu-238.",
        "Pu-238's half life is 87.7 years.",
        "A plutonium RTG was used to power the New Horizons probe that visited Pluto in 2015.",
        "Po-210 can also be used for RTGs as it generates 140 W/g of decay heat due to its 138 day half life.",
        "Pa-231 is an isotope of protactinium that easily fissions, but it isn't quite fissile.",
        "Muons generated by matter-antimatter reactions can trigger nuclear fusion reactions at room temperature.",
        "Roughly 20% of U-235 nuclei will fail to fission when hit by a neutron. They become U-236 nuclei instead.",
        "Thorium reactors are really uranium reactors that convert thorium into U-233.",
        "Natural uranium consists of 99.284% U-238, 0.711% U-235, and 0.0055% U-234.",
        "Most nuclear reactors use uranium that has been enriched to 3-5% U-235.",
        "Uranium-based nuclear weapons require uranium enriched to at least 85-90% U-235.",
        "Depleted uranium is uranium that has had most of its U-235 removed. It is effectively pure U-238.",
        "In the 1920s, uranium was considered a useless byproduct of the production of radium.",
        "The Manhattan Project referred to refined natural uranium as tuballoy, enriched uranium as oralloy, and depleted uranium as depletalloy."
    };

    private final short heat;
    private final boolean showsFacts;
    private boolean doesDecay;
    private long maxLifespan;
    private Supplier<Item> decayItem;

    public RtgPelletItem(final int heat, final boolean showsFacts) {
        super(new Item.Properties().stacksTo(1));
        this.heat = (short) heat;
        this.showsFacts = showsFacts;
    }

    public RtgPelletItem setDecays(final Supplier<Item> decayItemSupplier, final long lifespan) {
        this.doesDecay = true;
        this.decayItem = decayItemSupplier;
        this.maxLifespan = lifespan;
        return this;
    }

    public short getHeat() {
        return this.heat;
    }

    public boolean doesDecay() {
        return this.doesDecay;
    }

    public long getMaxLifespan() {
        return this.maxLifespan;
    }

    public @Nullable ItemStack getDecayItem() {
        if (!this.doesDecay || this.decayItem == null) {
            return null;
        }
        return new ItemStack(this.decayItem.get());
    }

    public long getLifespan(final ItemStack stack) {
        if (!this.doesDecay) {
            return 0L;
        }
        final CompoundTag tag = stack.getOrCreateTag();
        if (!tag.contains(TAG_DEPLETION)) {
            tag.putLong(TAG_DEPLETION, this.maxLifespan);
        }
        return tag.getLong(TAG_DEPLETION);
    }

    public short getScaledPower(final ItemStack stack) {
        if (!this.doesDecay || this.maxLifespan <= 0L) {
            return this.heat;
        }
        return (short) Math.ceil(this.heat * ((double) this.getLifespan(stack) / (double) this.maxLifespan));
    }

    public int getCurrentPower(final ItemStack stack, final boolean scaleWithDecay) {
        if (!this.doesDecay || !scaleWithDecay) {
            return this.heat;
        }
        return this.getScaledPower(stack);
    }

    public void decay(final ItemStack stack) {
        if (!this.doesDecay) {
            return;
        }
        final CompoundTag tag = stack.getOrCreateTag();
        final long next = Math.max(0L, Math.min(this.maxLifespan, this.getLifespan(stack) - 1L));
        tag.putLong(TAG_DEPLETION, next);
    }

    public static ItemStack handleDecay(final ItemStack stack) {
        if (!(stack.getItem() instanceof RtgPelletItem pellet) || !pellet.doesDecay()) {
            return stack;
        }
        if (pellet.getLifespan(stack) <= 0L) {
            final ItemStack decayStack = pellet.getDecayItem();
            return decayStack == null ? stack : decayStack;
        }
        pellet.decay(stack);
        return stack;
    }

    public static long getLifespanFromHalfLife(final float halfLife, final HalfLifeType type, final boolean realYears) {
        final float life;
        switch (type) {
            case LONG -> life = (48000F * (realYears ? 365F : 100F) * 100F) * halfLife;
            case MEDIUM -> life = (48000F * (realYears ? 365F : 100F)) * halfLife;
            case SHORT -> life = 48000F * halfLife;
            default -> throw new IllegalStateException("Unhandled half life type: " + type);
        }
        return (long) life;
    }

    @Override
    public @NotNull InteractionResultHolder<ItemStack> use(final Level level, final Player player, final InteractionHand usedHand) {
        final ItemStack stack = player.getItemInHand(usedHand);
        if (this.showsFacts && !level.isClientSide) {
            final RandomSource random = level.getRandom();
            final Component line = Component.literal(FACTS[random.nextInt(FACTS.length)]).withStyle(ChatFormatting.YELLOW);
            player.displayClientMessage(line, true);
            level.playSound(null, player.blockPosition(), SoundEvents.EXPERIENCE_ORB_PICKUP, SoundSource.PLAYERS, 1.0F, 1.0F);
        }
        return InteractionResultHolder.sidedSuccess(stack, level.isClientSide());
    }

    @Override
    public boolean isBarVisible(final ItemStack stack) {
        return this.doesDecay && this.getLifespan(stack) != this.maxLifespan;
    }

    @Override
    public int getBarWidth(final ItemStack stack) {
        if (!this.doesDecay || this.maxLifespan <= 0L) {
            return 13;
        }
        return Math.max(0, Math.round(13.0F * ((float) this.getLifespan(stack) / (float) this.maxLifespan)));
    }

    @Override
    public void appendHoverText(final ItemStack stack, @Nullable final Level level, final List<Component> tooltip, final TooltipFlag flag) {
        tooltip.add(Component.translatable(this.getDescriptionId() + ".desc"));
        tooltip.add(Component.translatable("desc.item.rtgHeat", this.getCurrentPower(stack, true)));
        if (!this.doesDecay) {
            return;
        }

        final ItemStack decayStack = this.getDecayItem();
        if (decayStack != null) {
            tooltip.add(Component.translatable("desc.item.rtgDecay", decayStack.getHoverName()));
        }

        final double ratio = this.maxLifespan <= 0L ? 0.0D : (double) this.getLifespan(stack) / (double) this.maxLifespan;
        tooltip.add(Component.literal(String.format(Locale.ROOT, "%.2f%%", ratio * 100.0D)));

        if (flag.isAdvanced()) {
            tooltip.add(Component.literal("EXTENDED INFO:"));
            tooltip.add(Component.literal(String.format(Locale.ROOT, "%d / %d ticks", this.getLifespan(stack), this.maxLifespan)));
        }
    }
}



